# Generated by Django 5.2.3 on 2025-06-25 10:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='cpr',
            field=models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator('^\\d{9}$', 'CPR must be exactly 9 digits.')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_no',
            field=models.CharField(help_text='Employee ID number', max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'Only numbers are allowed.')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone1',
            field=models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^\\d{8}$', 'Phone must be 8 digits.')]),
        ),
    ]
