# Generated by Django 5.2.3 on 2025-06-27 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_employee_is_active_alter_employee_cpr_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=100, unique=True)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('is_returnable', models.BooleanField(default=True, help_text='True = item must be returned')),
                ('has_expiry', models.BooleanField(default=False, help_text='True = item has expiry date')),
                ('unit', models.CharField(help_text='e.g. pcs, box, liters', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='item_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory_category')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemStoreStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, help_text='Size label (e.g., S, M, L, XL)', max_length=50, null=True)),
                ('quantity_original', models.PositiveIntegerField(help_text='Original received quantity')),
                ('quantity_current', models.PositiveIntegerField(help_text='Current available quantity')),
                ('item', models.ForeignKey(help_text='Reference to the inventory item', on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory_item')),
                ('store', models.ForeignKey(help_text='Reference to the store', on_delete=django.db.models.deletion.CASCADE, to='employees.store')),
            ],
        ),
        migrations.CreateModel(
            name='SizeVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_label', models.CharField(help_text='e.g., S, M, L, 42, XL', max_length=50)),
                ('quantity_original', models.PositiveIntegerField(default=0, help_text='Original quantity received')),
                ('quantity_current', models.PositiveIntegerField(default=0, help_text='Current available quantity')),
                ('item', models.ForeignKey(help_text='Reference to the inventory item', on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory_item')),
            ],
        ),
        migrations.CreateModel(
            name='StockReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_no', models.CharField(max_length=50, unique=True)),
                ('received_date', models.DateTimeField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.store')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='StockReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_received', models.PositiveIntegerField()),
                ('unit', models.CharField(help_text='Unit for this batch (e.g., pcs, box, liters)', max_length=20)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory_item')),
                ('size_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.sizevariant')),
                ('stock_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_items', to='inventory.stockreceipt')),
            ],
        ),
    ]
